legion-platform/legion

- deploy/ansible/roles/certificates/defaults/main.yml
- deploy/ansible/roles/certificates/tasks/main.yml
- deploy/ansible/roles/dns_records/tasks/main.yml
- deploy/ansible/roles/helm/tasks/main.yml
- deploy/ansible/roles/k8s/tasks/main.yml
- deploy/ansible/roles/k8s_dashboard/defaults/main.yml
- deploy/ansible/roles/k8s_dashboard/tasks/main.yml
- deploy/ansible/roles/k8s_dashboard/templates/dashboard-values.yaml.j2
- deploy/ansible/roles/legion_chart/templates/legion-values.yaml.j2
- deploy/ansible/site.yml
- deploy/helms/legion/templates/edge/edge-server.yaml
- deploy/helms/legion/templates/edi/edi-server.yaml
- deploy/helms/legion/templates/jenkins/jenkins-server.yaml
- deploy/helms/legion/templates/jupyter/nfs-webserver.yaml
- deploy/helms/legion/templates/ldap/ldap-gui.yaml
- deploy/helms/legion/templates/metrics/grafana.yaml
- deploy/helms/legion/templates/nexus/nexus-ingress.yaml
- deploy/profiles/nightly_single_master.ansible.yml
- deploy/profiles/super_master.ansible.yml
In order to generate single certificate for all cluster I replaces ACMEv1 request with ACMEv2 request and now ansible issues single wildcard certificate for each cluster.
> Wildcard certificate

- k8s/airflow/create_secrets.py
In order to keep valid version of airflow connections I've added removing of connections before creation
> Add process of removing connections before creation for airflow

- k8s/airflow/Dockerfile
In order to fix error that appeared after new version of PIP - now pip version has been freezed in Dockerfile
> Freeze pip version

- deploy/ansible/deploy-legion-enclave.yml
- deploy/ansible/roles/helm/tasks/main.yml
- deploy/ansible/terminate-legion-enclave.yml
- deploy/deploy-legion-enclave.Jenkinsfile
- deploy/profiles/legion-ci.epm.kharlamov.biz.yml
- deploy/profiles/legion-dev.epm.kharlamov.biz.yml
- deploy/profiles/legion-test.epm.kharlamov.biz.yml
- deploy/terminate-legion-enclave.Jenkinsfile
- tests/1_check_airflow.robot
- tests/2_check_models.robot
- tests/load_variables_from_profiles.py
There are two jenkins files with appropriate ansible playboks for Enclace deployment and termination.
> [#43] Introduce functionality to create/delete enclaves

- deploy/ansible/roles/k8s_resources/defaults/main.yml
- deploy/ansible/roles/k8s_resources/tasks/main.yml
- deploy/ansible/roles/k8s_resources/tasks/prometheus.yaml
- deploy/ansible/roles/k8s_resources/templates/prometheus.yml.j2
> [#49] Add grafana and prometeus support

- deploy/profiles/legion-demo.epm.kharlamov.biz.yml
> [#64] Add profile for new demo env type

- deploy/ansible/roles/helm/tasks/main.yml
- deploy/ansible/roles/k8s_create_cluster/defaults/main.yaml
- deploy/ansible/roles/k8s_create_cluster/templates/kops.yaml.j2
- deploy/ansible/roles/k8s_resources/tasks/dashboard.yaml
- deploy/ansible/roles/k8s_resources/templates/autoscaler.yaml.j2
- deploy/ansible/roles/k8s_resources/templates/dashboard.ing.yml.j2
- deploy/profiles/legion-ci.epm.kharlamov.biz.yml
- deploy/profiles/legion-dev.epm.kharlamov.biz.yml
- deploy/profiles/legion-test.epm.kharlamov.biz.yml
- examples/Digit-Recognition/Jenkinsfile
- examples/MovieLens/Jenkinsfile
- examples/Sklearn-Income/Jenkinsfile
- examples/Test-Summation/Jenkinsfile
- examples/Vertical-Scaling/performance.Jenkinsfile
- k8s/jenkins/legion-jenkins-plugin/src/main/resources/legion.groovy
- k8s/jenkins/plugins.txt
- tests/2_check_models.robot
This PR fixes issues #41 
And #58 as well
From user's perspective just need to define desired memory and CPU resources and AWS instances with optimal shape would be created and delete automatically
> [#41][#58][#60] Add multi shape support for Kops cluster and addon's improvements

- Jenkinsfile
- deploy/create-cluster.Jenkinsfile
- deploy/deploy-legion.Jenkinsfile
- deploy/terminate-cluster.Jenkinsfile
This closes #55: this adds filtering for slack messages (only messages for develop and master branch with R->G, G->R, R->R states would be sent)
> [#55] Jenkins notification filtering based on branch and state transition

- Jenkinsfile
- k8s/jenkins/Dockerfile
- k8s/jenkins/legion-jenkins-plugin/pom.xml
- k8s/jenkins/plugins.txt
- k8s/jenkins/scripts/install-plugins.sh
> [#74] Use specific (not last) version for Jenkins plugin in build process

- deploy/helms/legion-core/templates/jenkins/jenkins-pvc.yaml
- deploy/helms/legion-core/templates/jenkins/jenkins-server.yaml
- deploy/helms/legion-core/values.yaml
- k8s/jenkins/chmod-docker-and-run-jenkins.sh
- k8s/jenkins/scripts/create_jobs.groovy
> [#28] Persistent volume for Jenkins workspace to survive after restarts

- deploy/ansible/roles/airflow_chart/tasks/main.yml
- deploy/ansible/roles/certificates/tasks/install.yaml
- deploy/ansible/roles/charts_common/tasks/main.yml
- deploy/ansible/roles/helm/tasks/main.yml
- deploy/ansible/roles/k8s_create_cluster/tasks/create-cluster.yaml
- deploy/ansible/roles/k8s_resources/tasks/autoscaler.yaml
- deploy/ansible/roles/k8s_resources/tasks/dashboard.yaml
- deploy/ansible/roles/k8s_resources/tasks/ingress.yaml
- deploy/ansible/roles/k8s_resources/tasks/prometheus.yaml
- deploy/ansible/roles/k8s_resources/tasks/pvc.yaml
- deploy/ansible/roles/legion_chart/tasks/install_enclave.yml
- deploy/ansible/roles/legion_core_chart/tasks/main.yml
- deploy/ansible/terminate-legion-enclave.yml
- deploy/profiles/legion-demo.epm.kharlamov.biz.yml
[#54] kubectl and helm options for parallel job execution
> [#54] kubectl and helm options for parallel job execution 

- deploy/ansible/roles/legion_chart/tasks/install_enclave.yml
- deploy/ansible/roles/legion_core_chart/tasks/main.yml
- deploy/helms/legion/templates/enclave.networkpolicy.yaml
Added networkpolicy to isolate enclave components
Fixes issue #57
> [#57] Implement enclave networkpolicy

- legion_test/requirements/base.txt
legion_test's Jinja version has been updated to the same as legion's Jinja version
> [#45] Allow simultanious installation of legion and legion_test 

- deploy/ansible/roles/k8s_terminate_cluster/tasks/main.yaml
> [#90] Check if the cluster exists before termination

- deploy/ansible/roles/k8s_create_cluster/tasks/create-cluster.yaml
- deploy/ansible/roles/k8s_resources/tasks/autoscaler.yaml
- deploy/ansible/roles/k8s_resources/tasks/dashboard.yaml
- deploy/ansible/roles/k8s_resources/tasks/ingress.yaml
- deploy/ansible/roles/k8s_resources/tasks/prometheus.yaml
- deploy/ansible/roles/k8s_resources/tasks/pvc.yaml
- deploy/profiles/legion-ci.epm.kharlamov.biz.yml
- deploy/profiles/legion-demo.epm.kharlamov.biz.yml
- deploy/profiles/legion-dev.epm.kharlamov.biz.yml
- deploy/profiles/legion-test.epm.kharlamov.biz.yml
[#54] change cluster templates names to {{ tmp_dir }}\template_name.{cluster_name}}.yml format
https://jenkins.cc.epm.kharlamov.biz/jenkins/job/Create_cluster/133/console
> [#54] Ansible template file names for parallel job execution

- deploy/full-lifecycle.Jenkinsfile
> Add pipeline for Legion full lifecycle tests

- deploy/ansible/roles/k8s_create_cluster/tasks/create-cluster.yaml
- deploy/profiles/legion-demo.epm.kharlamov.biz.yml
> Check that all masters are ready before proceeding

- deploy/ansible/create-cluster.yml
- deploy/ansible/deploy-legion.yml
- deploy/ansible/roles/helm/tasks/main.yml
> Prometeus installation fails

- deploy/ansible/roles/k8s_resources/tasks/ingress.yaml
- deploy/ansible/roles/legion_enclave/tasks/create_enclave.yml
> Fix mistype in enclave creation playbook 

- legion_test/legion_test/robot/k8s.py
- tests/0_check_clusterwide.robot
- tests/1_check_airflow.robot
- tests/2_check_models.robot
- tests/3_check_flower.robot
- tests/load_variables_from_profiles.py
> [#113] Allow robot tests simultanious run

- deploy/ansible/roles/legion_core_chart/tasks/main.yml
- deploy/ansible/roles/legion_enclave/tasks/create_enclave.yml
- deploy/ansible/roles/legion_enclave/tasks/install_airflow.yml
- deploy/ansible/roles/legion_enclave/tasks/install_legion.yml
Will work now, later should be refactored in future to store all cluster related data in /dir/cluster/files format
> [#134] Fixes intermittent deployment failure due a race condition

- deploy/full-lifecycle.Jenkinsfile
- legion_test/legion_test/templates/jenkins_job.tmpl
- legion_test/legion_test/templates/jenkins_performance_job.tmpl
- tests/1_check_airflow.robot
This PR resolves #136 issue
Do not merge! Testing CI on this job right now.
> [#136] Add refspec for PR builder to Model jobs

- deploy/ansible/roles/legion_enclave/tasks/install_airflow.yml
- deploy/ansible/roles/legion_enclave/templates/airflow-values.yaml.j2
- deploy/full-lifecycle.Jenkinsfile
- deploy/helms/airflow/templates/configuration.yaml
- deploy/helms/airflow/templates/web.yaml
- deploy/helms/airflow/values.yaml
- legion_test/legion_test/robot/airflow.py
- tests/1_check_airflow.robot
this PR resolves #142 
What's been done:
- decreased airflow worker refresh interval
- updated airflow webserver readiness probe
- removed hardcoded timeout during test stage
- added debug mode for further purposes
> [#142] Improve Airflow start up speed

- Jenkinsfile
- deploy/ansible/roles/k8s_terminate_cluster/tasks/main.yaml
resolves #137 
Build time decreased from about 6mins to 2mins
> [#137] decrease legion build time

- legion_test/bin/cleanup_nexus_repo
> [#144] Nexus artifacts cleanup

- deploy/ansible/roles/legion_enclave/templates/airflow-values.yaml.j2
- deploy/helms/airflow/templates/worker.yaml
- deploy/helms/airflow/values.yaml
- k8s/airflow/Dockerfile
This PR closes #189 .
Added legion python package to airflow, to use legions classes (such as ModelClient)
> [#189] Added legion python package to Airflow

- deploy/ansible/create-cluster.yml
- deploy/ansible/deploy-legion-enclave.yml
- deploy/ansible/deploy-legion.yml
- deploy/ansible/terminate-cluster.yml
- deploy/ansible/terminate-legion-enclave.yml
- deploy/create-cluster.Jenkinsfile
- deploy/deploy-legion-enclave.Jenkinsfile
- deploy/deploy-legion.Jenkinsfile
- deploy/legionPipeline.groovy
- deploy/terminate-cluster.Jenkinsfile
- deploy/terminate-legion-enclave.Jenkinsfile
> Custom profiles and shared pipeline methods

- deploy/ansible/roles/k8s_resources/tasks/dex.yaml
> [#200] Change Dex DNS ttl

- deploy/ansible/create-cluster.yml
- deploy/ansible/deploy-legion-enclave.yml
- deploy/ansible/deploy-legion.yml
- deploy/ansible/terminate-legion-enclave.yml
- deploy/legionPipeline.groovy
- deploy/profiles/legion-ci.epm.kharlamov.biz.yml
- deploy/profiles/legion-demo.epm.kharlamov.biz.yml
- deploy/profiles/legion-dev.epm.kharlamov.biz.yml
- deploy/profiles/legion-test.epm.kharlamov.biz.yml
[#191] Ansible-vault legion integration
> [#191] Ansible-vault legion s3 integration

- deploy/legionPipeline.groovy
Fix overlap of Profile variable
> Fix Profile message on slack notification

- deploy/legionPipeline.groovy
- tests/robot/0_check_clusterwide.robot
- tests/robot/1_check_airflow.robot
- tests/robot/2_check_models.robot
- tests/robot/3_check_flower.robot
- tests/robot/4_check_edi.robot
Add support of custom profiles location at test phase
> Fix tests for custom profiles location

- .gitignore
- deploy/ansible/roles/k8s_resources/tasks/dex.yaml
> [#217] fix dex chart status check

- deploy/build-and-deploy-legion.Jenkinsfile
> [#198] build and deploy pipeline

- deploy/legionPipeline.groovy
This PR fixes slack notifications errors on jobs without LocalVersion
> Fixes Slack notifications for errors on jobs without LocalVersion

- legion/tests/legion_test_utils.py
- legion/tests/test_utils_external_file.py
> [#89] httpbin in docker

- legion/legion/version.py
> [#228] Bump legion version to 0.6.0

- deploy/ansible/roles/aws_resources/tasks/airflow-efs.yml
- deploy/ansible/roles/aws_resources/tasks/airflow-rds.yml
- deploy/ansible/roles/k8s_create_cluster/templates/kops.yaml.j2
> [#237] consolidate aws tags

- deploy/legionPipeline.groovy
- legion_test/legion_test/profiler_loader.py
- tests/python/test_k8s_introspection.py
- tests/python/test_k8s_model_operations.py
- tests/python/test_k8s_watching.py
- tests/robot/5_check_edi_milti_versioned_models.robot
Now we need to enter only comma separated tags in TestTags field which includes tests both from robot and nose.
Nose test profile dir fix.
Nose tests tags added.
> [#246] Simplify tag including in tests run

- deploy/ansible/create-cluster.yml
- deploy/profiles/secrets_template.yaml
#264 Fixed profile and secret validator: invalid property name and wrong template path to.
Validated profile & secret for Legion-demo.
> [#264] Fixed profile validator

- k8s/edge/nginx.conf.ltmpl
- legion/legion/k8s/services.py
> Fix EDGE 503 error with using Service ClusterIP

- deploy/full-lifecycle.Jenkinsfile
> [#266] ci pipeline tests tags

- legion/bin/legionctl
- legion/legion/edi/deploy.py
Flags `no-wait` and `timeout` would be added
> [#208] Add correct detecting models for undeploy

- legion/legion/external/edi.py
- legion/legion/k8s/enclave.py
- legion/legion/k8s/services.py
> [#212] Check legionctl scale value

- k8s/jenkins/legion-jenkins-plugin/src/main/resources/legion.groovy
> [#301] Fix logging on legion.groovy

- deploy/ansible/roles/k8s_resources/templates/provisioner.yaml.j2
> [#335] pin efs-provisioner version

- deploy/ansible/roles/legion_enclave/tasks/create_enclave.yml
> [#349] Fix kubectl context selection

- legion/legion/version.py
> [#299] bump version to 0.8.0

- deploy/ansible/roles/aws_resources/tasks/jenkins-volume.yml
- deploy/ansible/roles/aws_resources/tasks/main.yml
- deploy/ansible/roles/k8s_resources/tasks/jenkins-volume.yaml
- deploy/ansible/roles/k8s_resources/tasks/main.yml
- deploy/ansible/roles/k8s_resources/templates/jenkins-volume.yaml.j2
- deploy/ansible/roles/k8s_terminate_cluster/tasks/jenkins-volume.yml
- deploy/ansible/roles/k8s_terminate_cluster/tasks/main.yaml
- deploy/ansible/roles/legion_core_chart/tasks/main.yml
- deploy/ansible/roles/legion_core_chart/templates/legion-core-values.yaml.j2
- deploy/legionPipeline.groovy
- deploy/profiles/legion-ci.epm.kharlamov.biz.yml
- deploy/profiles/legion-demo.epm.kharlamov.biz.yml
- deploy/profiles/legion-dev.epm.kharlamov.biz.yml
- deploy/profiles/profiles_template.yaml
This PR implements persistent volume for Jenkins
> [#296] Persistent volume for Jenkins workspace

- legion/bin/legionctl
- legion/legion/edi/deploy.py
- legion/legion/edi/server.py
- legion/legion/external/edi.py
- legion/legion/http.py
- legion/legion/k8s/definitions.py
- legion/legion/k8s/enclave.py
- legion/legion/utils.py
- tests/robot/4_check_edi.robot
- tests/robot/5_check_edi_multi_versioned_models.robot
This closes #330, #331.
This adds correct logic, that analyze cluster status after models state will be modified
> [#331][#330] Add valid checking in legionctl after legionctl command

- k8s/jenkins/legion-jenkins-plugin/src/main/resources/legion.groovy
> [#370] Add Enclave param validation for Cluster's Jenkins

- legion_test/legion_test/robot/utils.py
- tests/robot/0.1_check_components_auth.robot
- tests/robot/0.2_check_clusterwide.robot
- tests/robot/resources/keywords.robot
**Three tests group added:**
- check the presence of the auth
- check invalid auth
- check valid auth
**Current tests covers:**
Jenkins, Nexus, Grafana(cluster and enclave), Flower, Airflow
> [#323] Legion components authorization tests added

- deploy/ansible/roles/legion_enclave/tasks/install_airflow.yml
- deploy/ansible/roles/legion_enclave/templates/airflow-values.yaml.j2
- deploy/helms/airflow/templates/web.yaml
- deploy/helms/airflow/templates/worker-rbac.yaml
- deploy/helms/airflow/templates/worker.yaml
- deploy/helms/airflow/values.yaml
- legion_airflow/legion_airflow/hooks/k8s_base_hook.py
- legion_airflow/legion_airflow/hooks/s3_hook.py
- legion_test/legion_test/robot/airflow.py
Implement a new hook class that gets connection from k8s secret storage and if failed to do so invokes parent method to get connection. Use it as base for other hooks from now on. #253 
During this feature I had to fix #277 
this PR closes #253 #277
> [#253] Airflow hook for reading from K8S secrets

- tests/robot/4_check_edi.robot
Fixes misspelling of the test variable.
> [#358] Fixes model_id variable name in 2 tests

- deploy/ansible/roles/k8s_resources/templates/prometheus.yml.j2
> [#327] Secure prometheus ingress components

- Jenkinsfile
> [#404] Return build description

- deploy/ansible/roles/k8s_resources/tasks/kube-elb-security.yaml
- deploy/ansible/roles/k8s_resources/tasks/main.yml
- deploy/helms/kube-elb-security/.helmignore
- deploy/helms/kube-elb-security/Chart.yaml
- deploy/helms/kube-elb-security/templates/_helpers.tpl
- deploy/helms/kube-elb-security/templates/deployment.yaml
- deploy/helms/kube-elb-security/templates/rbac.yaml
- deploy/helms/kube-elb-security/values.yaml
Build of a plugin would be moved to this repo on separate PR
> [#112] Add Kube ELB security plugin deployment

- deploy/ansible/roles/k8s_resources/tasks/cluster-groups.yaml
- deploy/ansible/roles/legion_core_chart/templates/legion-core-values.yaml.j2
- deploy/ansible/roles/legion_enclave/templates/airflow-values.yaml.j2
- deploy/profiles/secrets_template.yaml
- legion_airflow/legion_airflow/auth/dex_auth.py
This PR includes PR #424 and solves issue #423 and #422 
Requires secrets update
> [#422] Update dex groups mapping

- legion/legion/containers/docker.py
- legion/legion/templates/Dockerfile.tmpl
- legion/tests/legion_test_utils.py
- legion/tests/test_deploy.py
- legion/tests/test_models/complex_model/run.py
> [#406] Add symlink in model pods

- legion/legion/serving/pyserve.py
> [#37] Remove old grafana code

- k8s/edge/Dockerfile
> [#457] Fix nginx-jwt dependency installation

- k8s/edge/Dockerfile
This closes #464 
This affects #375
> [#464] Add pandas to EDGE Dockerfile

- Jenkinsfile
- k8s/edge/Dockerfile
> [#469] Add copying all dependencies to EDGE image

- legion_test/legion_test/process_reporter.py
- legion_test/legion_test/profiler_loader.py
- legion_test/legion_test/robot/__init__.py
- legion_test/legion_test/robot/framework_extensions.py
- legion_test/legion_test/robot/process.py
- tests/robot/4_check_edi.robot
- tests/robot/5_check_edi_multi_versioned_models.robot
- tests/robot/resources/keywords.robot
> [#383] Add Run Process without PIPE action to Robot Tests

- legion_test/legion_test/robot/airflow.py
- tests/robot/1_check_airflow.robot
- tests/robot/resources/keywords.robot
- tests/robot/resources/variables.robot
Airflow API client was enhanced and robot tests was updated to execute Aiflow dags in test mode and wait for a success completion.
> [#161] Trigger Airflow tasks in robot test and check status

- k8s/jenkins/plugins.txt
> [#485] Update durable-task plugin

- base-python-image/requirements.txt
> [#501] Pin ipykernel==4.9.0

- k8s/jenkins/legion-jenkins-plugin/src/main/resources/legion.groovy
It looks like you have tried to train and deploy model from Jenkinsfile that has been placed in the repository root. So, in this case current code works incorrectly and tries to copy log files from one directory to same directory. That is not linked with build number.
> [#301] Fix log storing in small Jenkins

- tests/robot/0.1_check_components_auth.robot
- tests/robot/2_check_models.robot
- tests/robot/4_check_edi.robot
- tests/robot/5_check_edi_multi_versioned_models.robot
> [#432] Update robot tests tags

- deploy/ansible/roles/k8s_terminate_cluster/tasks/kube2iam.yaml
- deploy/ansible/roles/legion_enclave/tasks/create_enclave.yml
- deploy/helms/event-collector/templates/fluentd/fluentd-server.yaml
> [#530] update event collector role name

- legion_airflow/legion_airflow/hooks/s3_hook.py
CSV writer and reader in S3Hook were fixed, added columns number validation on CSV read.
This PR closes #521
> [#521] CSV writer and reader in S3Hook were fixed

- deploy/ansible/roles/k8s_resources/templates/dex.yml.j2
- deploy/helms/dex/templates/secret.yaml
- deploy/profiles/secrets_template.yaml
> [#527] Extend Dex config flexibility

- legion_test/bin/cleanup_nexus_repo
> [#536] update date pattern

- base-python-image/requirements.txt
> [#312] Update Kubernetes API package to 6.0.0 version

- tests/python/test_k8s_model_operations.py
- tests/python/test_k8s_properties_storages.py
- tests/python/test_k8s_watching.py
> [#475] Remove sleeps in regression tests

- .gitforbidden
- .gitwhitelisted
- Jenkinsfile
- deploy/ansible/roles/legion_enclave/templates/airflow-values.yaml.j2
- deploy/helms/airflow/values.yaml
- deploy/helms/dex/values.yaml
- deploy/helms/legion/templates/edi/edi-secrets.yaml
- deploy/helms/legion/values.yaml
- deploy/profiles/legion-ci-app.epm.kharlamov.biz.yml
- deploy/profiles/legion-ci-infra.epm.kharlamov.biz.yml
- deploy/profiles/legion-ci.epm.kharlamov.biz.yml
- deploy/profiles/legion-demo.epm.kharlamov.biz.yml
- deploy/profiles/legion-dev.epm.kharlamov.biz.yml
- deploy/profiles/legion-test.epm.kharlamov.biz.yml
- install-git-secrets-hook.sh
- legion/docs/source/configuration.md
- legion_airflow/legion_airflow/hooks/k8s_base_hook.py
- legion_test/legion_test/profiler_loader.py
- legion_test/legion_test/robot/utils.py
- tests/robot/resources/variables.robot
> [#493] Add parsing source codes

- legion_airflow/legion_airflow/auth/dex_auth.py
- legion_airflow/legion_airflow/hooks/k8s_base_hook.py
- legion_airflow/legion_airflow/hooks/s3_handler.py
- legion_airflow/legion_airflow/hooks/s3_hook.py
- legion_airflow/tests/test_csv.py
This PR closes #521 .
Fixed CSV reader to read rows cells with commas and quotes
> [#521] Fixed CSV reader to read rows cells with commas and quotes

- legion_test/legion_test/robot/jenkins.py
> [#539] Add gathering Jenkins logs

- k8s/kube-fluentd/fluent.conf
This PR fixes issue with Fluentd-s3 config prefix
> Fix Fluentd logging s3 Prefix

- deploy/helms/legion/templates/edge/edge-server.yaml
- k8s/edge/Dockerfile
- k8s/edge/nginx.conf.ltmpl
- k8s/edge/start.sh
- legion/legion/template.py
- legion/legion/template_plugins/k8s.py
- legion/legion/template_plugins/os_environ.py
This PR closes #579 
I've moved healthcheck endpoint definition to the end of config otherwise it's replaced by **location /**
> [#579] Fixed healthcheck endpoint in nginx config

- deploy/helms/airflow/templates/web.yaml
> [#277] Changed Probes for Airflow Web pod, extended timeouts

- legion_test/legion_test/robot/flower.py
- legion_test/legion_test/robot/k8s.py
- tests/robot/tests/1_common/1.3_check_flower.robot
> [#583] Flower scale up and down tests fixed

- legion/tests/test_legion-template.py
> [#585] Fix unit tests for templates

- legion/legion/http.py
- legion/legion/model/client.py
- legion/tests/test_pyserve.py
> [#272] Remove exception on empty list in batch invocation

- deploy/ansible/roles/k8s_create_cluster/defaults/main.yaml
- deploy/profiles/legion-ci-app.epm.kharlamov.biz.yml
- deploy/profiles/legion-ci-infra.epm.kharlamov.biz.yml
- deploy/profiles/legion-ci.epm.kharlamov.biz.yml
- deploy/profiles/legion-demo.epm.kharlamov.biz.yml
- deploy/profiles/legion-dev.epm.kharlamov.biz.yml
- deploy/profiles/legion-test.epm.kharlamov.biz.yml
- deploy/profiles/profiles_template.yaml
This PR partially solves issue #577 
and soleves issue #567
> [#577] Bump up kops and kubernetes

- Jenkinsfile
- deploy/ci-app.Jenkinsfile
- deploy/ci-full-lifecycle.Jenkinsfile
- deploy/ci-infra.Jenkinsfile
- deploy/legionPipeline.groovy
> [#513] Add notifications to Jenkins deploy jobs

- legion_test/legion_test/robot/flower.py
- legion_test/legion_test/robot/k8s.py
this closes #613 
- Fix the way of counting active workers
- Logging to test methods added
> [#613] Count online workers from flower in correct way

- k8s/airflow/Dockerfile
- legion_test/legion_test/robot/airflow.py
- tests/robot/resources/keywords.robot
This PR closes #611 
Froze python packages versions in Airflow dockerfile and changed tests to check if any dags succeeded
> [#611] Froze python packages versions in Airflow dockerfile

- Jenkinsfile
- k8s/jenkins/Dockerfile
> [#309] Add proxy for jenkins plugins

- Jenkinsfile
> [#631] fix release tagging

- legion_test/requirements/base.txt
- tests/robot/resources/browser.robot
- tests/robot/tests/1_common/1.1_check_clusterwide.robot
Closes #626 
1. Change SeleniumLibrary to Selenium2Library - to work with tables.
2. Explicite waits added.
> [#626] Fix nexus ui tests

- Jenkinsfile
> [#566] Add helm packing and publishing to local repo

- deploy/ansible/roles/k8s_create_cluster/tasks/create-cluster.yaml
> [#647]  fix kubeapi elb healthcheck

- deploy/ansible/roles/k8s_create_cluster/defaults/main.yaml
> [#642] update k8s to 1.10.11

- deploy/ansible/roles/k8s_create_cluster/tasks/create-cluster.yaml
- deploy/ansible/roles/legion_enclave/defaults/main.yml
- deploy/ansible/roles/legion_enclave/templates/airflow-values.yaml.j2
- deploy/helms/airflow/templates/worker.yaml
- deploy/profiles/legion-ci-app.epm.kharlamov.biz.yml
- deploy/profiles/legion-ci-infra.epm.kharlamov.biz.yml
- deploy/profiles/legion-ci.epm.kharlamov.biz.yml
- deploy/profiles/legion-demo.epm.kharlamov.biz.yml
- deploy/profiles/legion-dev.epm.kharlamov.biz.yml
- deploy/profiles/legion-test.epm.kharlamov.biz.yml
- deploy/profiles/profiles_template.yaml
> [#639] set airflow worker limits in profile

- k8s/jenkins/legion-jenkins-plugin/src/main/resources/legion.groovy
Fixes legionctl deploy command.
This closes #651
> [#651] Fix legionctl deploy command to accept model version

- tests/robot/resources/keywords.robot
> [#641] Wait for dag run finish before checking it

- legion/legion/k8s/utils.py
- legion/tests/test_k8s.py
> [#654] pin registry version

- k8s/edge/edge.lua
- legion/docs/source/model_rest_api.md
- legion/legion/external/edi.py
- legion/legion/http.py
- legion/tests/legion_test_utils.py
- legion/tests/test_pyserve.py
- legion_test/bin/check_jenkins_jobs
- legion_test/bin/copyright_scanner
- legion_test/bin/create_example_jobs
- legion_test/bin/jenkins_dex_client
- legion_test/bin/legion_bootstrap_grafana
- tests/robot/resources/keywords.robot
* Created the separate parse_invoke_request function because the
parse_request function is used in other places
* Added unit tests
* Updated the rest api doc
This closes #671
> [#671] Invocation logic switch

- legion_test/bin/cleanup_nexus_repo
this fixes #675 
updated api endpoints for new nexus and proper exceptions handling
> [#675] Fix nexus cleanup script

- deploy/build-and-deploy-legion.Jenkinsfile
> [#700] add missed braces

- legion/legion/edi/server.py
- legion_test/legion_test/robot/grafana.py
- tests/robot/tests/4_edi_multi_versioned_models/4.0_check_edi_multi_versioned_models.robot
Fixed removing whole grafana dashboard when undeploying one version of multiversion model
> [#544] Fix removing grafana dashboard

- deploy/ci.Jenkinsfile
- tests/robot/tests/3_edi_one_model/3.0_check_edi_one_model.robot
> [#697] add post cleanup stage

- CHANGELOG.md
> [#679] Add changelog notes for 0.10.0 release

- CHANGELOG.md
- Jenkinsfile
> [#706] Missed param in CI

- deploy/ansible/roles/k8s_resources/defaults/main.yml
- deploy/ansible/roles/k8s_resources/tasks/k8s-authenticator.yaml
- deploy/ansible/roles/k8s_resources/tasks/kube-elb-security.yaml
- deploy/ansible/roles/k8s_resources/tasks/kube-fluentd.yaml
- deploy/ansible/roles/k8s_resources/tasks/oauth2-proxy.yaml
- deploy/ansible/roles/legion_core_chart/defaults/main.yaml
- deploy/ansible/roles/legion_core_chart/tasks/main.yml
- deploy/ansible/roles/legion_enclave/defaults/main.yml
- deploy/ansible/roles/legion_enclave/tasks/install_airflow.yml
- deploy/ansible/roles/legion_enclave/tasks/install_legion.yml
- deploy/build-and-deploy-legion.Jenkinsfile
- deploy/ci.Jenkinsfile
- deploy/create-cluster.Jenkinsfile
- deploy/deploy-legion-enclave.Jenkinsfile
- deploy/deploy-legion.Jenkinsfile
- deploy/legionPipeline.groovy
- deploy/profiles/legion-ci-app.epm.kharlamov.biz.yml
- deploy/profiles/legion-ci-infra.epm.kharlamov.biz.yml
- deploy/profiles/legion-ci.epm.kharlamov.biz.yml
- deploy/profiles/legion-demo.epm.kharlamov.biz.yml
- deploy/profiles/legion-dev.epm.kharlamov.biz.yml
- deploy/profiles/legion-test.epm.kharlamov.biz.yml
- deploy/terminate-cluster.Jenkinsfile
- deploy/terminate-legion-enclave.Jenkinsfile
- tests/robot/tests/3_edi_one_model/3.0_check_edi_one_model.robot
> [#682] run ansible from sources

- deploy/helms/legion/templates/edge/edge-server.yaml
- deploy/legionPipeline.groovy
- k8s/edge/Dockerfile
- k8s/edge/edge.lua
- k8s/edge/nginx.conf.ltmpl
- k8s/edge/request_id_generator.lua
- tests/robot/tests/5_feedback/5.1_check_feedback.robot
> [#710] Setting random seed in EDGE

- deploy/ansible/roles/legion_enclave/tasks/install_legion.yml
- deploy/ansible/roles/legion_enclave/templates/legion-values.yaml.j2
- deploy/profiles/secrets_template.yaml
> [#637] Make JWT secrets generate-able per enclave

- tests/robot/tests/1_common/1.0_check_components_auth.robot
- tests/robot/tests/1_common/1.2_check_airflow.robot
- tests/robot/tests/1_common/1.3_check_flower.robot
- tests/robot/tests/2_jenkins_models/2.0_check_jenkins_models.robot
- tests/robot/tests/3_edi_one_model/3.0_check_edi_one_model.robot
- tests/robot/tests/4_edi_multi_versioned_models/4.0_check_edi_multi_versioned_models.robot
- tests/robot/tests/5_feedback/5.1_check_feedback.robot
> [#715] clean up the robot test tags

- legion_test/bin/cleanup_nexus_repo
> [#717] update list of allowed nexus response codes

- install-git-secrets-hook.sh
> [#738] Fix hanging of git pre-commit hook installation

- k8s/edi/uwsgi.ini
> [#740] Remove cheaping

- legion/requirements/Pipfile
- legion/requirements/Pipfile.lock
- legion/tests/test_utils_external_file.py
* Mocked requests library using responses
> [#714] Fixed unstable test_external_file_reader_http_example unit test

- tests/robot/resources/browser.robot
- tests/robot/tests/1_common/1.1_check_clusterwide.robot
> [#741] Remove unstable test

- deploy/ansible/roles/k8s_resources/templates/autoscaler.yaml.j2
> [#445] update autscaler intervals

- CHANGELOG.md
- Jenkinsfile
- deploy/ansible/roles/charts_common/tasks/main.yml
> [#776] deploy stable release

- CHANGELOG.md
- legion/legion/version.py
> Set release version to 0.11.0

- deploy/ci.Jenkinsfile
> [#714] Fixed Jenkins job description

- examples/Sklearn-Income/tests/test_basic.py
This closes #773 
Fix model version when generationg JWT
> [773] fix Sklearn-income test
