legion_test/bin/create_example_jobs

This closes #42 
Previously while importing jobs, job was ignored if a job with the same existed. Now if there is a job with same name, existing job is reconfigured.
Code is tested locally on dev cluster.

[#42] Changed create_example_jobs, now reconfiguring existing job

---

tests/2_check_models.robot

This PR fixes error, that has been merged in PR #67 
Error consists of typo in Robot tests.

[#41] Repair code of tests K8S autoscaler

---

Jenkinsfile

This closes #157 
Wrong python interpreter (default) call has been changed to correct (python in virtualenv)

[#157] Fix documentation publishing process

---

deploy/helms/legion/templates/edi/edi-server.yaml
k8s/edi/Dockerfile
k8s/edi/app_uwsgi.ini
k8s/edi/chmod-docker-and-run-edi.sh
k8s/edi/nginx.conf
k8s/edi/supervisord.conf
k8s/edi/uwsgi.ini
legion/legion/edi/wsgi.py

This closes #152 
Built-in flask HTTP server has been replaced with nginx uwsgi

[#152] Production ready serving for edi

---

deploy/ansible/roles/legion_enclave/templates/legion-values.yaml.j2

This PR enables Dex auth on enclave grafana when dex is enabled

Enable dex auth on enclave grafana ingress

---

deploy/helms/airflow/values.yaml

Changed  "dex_admin_email" parameter from "admin@example.com" to "tests@legion.com" for working tests.

[#247] fix airflow deploy default values

---

deploy/helms/airflow/templates/web.yaml

#277 
Airflow Web pod slows down due to a number of DAGs. LivenessProbe is unable to get response in specified timeout. Thus Airflow Web is unavailable.

[#277] Increased Airflow web probes timeout to 2 secs

---

deploy/ansible/roles/legion_core_chart/tasks/main.yml
deploy/ansible/roles/legion_enclave/tasks/create_enclave.yml
deploy/ansible/roles/legion_enclave/templates/airflow-values.yaml.j2
deploy/ansible/roles/legion_enclave/templates/airflow_s3_access_policy.yaml.j2
deploy/helms/airflow/templates/configuration.yaml
deploy/profiles/legion-ci.epm.kharlamov.biz.yml
deploy/profiles/legion-demo.epm.kharlamov.biz.yml
deploy/profiles/legion-dev.epm.kharlamov.biz.yml
deploy/profiles/profiles_template.yaml
legion/docs/source/configuration.md
legion_airflow/legion_airflow/hooks/s3_hook.py
legion_airflow/setup.py

Fixed S3Hook to load/write logs properly to/from S3. #270 
Previously it failed after Kube2IAM implementation. Not it works fine.
Notice: **airflow_s3_log_url** profile property format has been changed.

[#270] Fixed S3Hook to load/write logs in S3 properly

---

legion/bin/legionctl
legion/legion/edi/deploy.py
legion/legion/external/edi.py
legion/legion/k8s/definitions.py
tests/robot/resources/keywords.robot

This closes #399.
Example:
```
legionctl --verbose scale test-summation 5 --edi https://edi-company-a.legion-dev.epm.kharlamov.biz
2018-08-30 20:35:15,036 - INFO - Sending scale request to EdiClient('https://edi-company-a.legion-dev.epm.kharlamov.biz')
2018-08-30 20:35:15,038 - DEBUG - Starting new HTTPS connection (1): edi-company-a.legion-dev.epm.kharlamov.biz
2018-08-30 20:35:17,104 - DEBUG - https://edi-company-a.legion-dev.epm.kharlamov.biz:443 "POST /api/1.0/scale HTTP/1.1" 200 None
2018-08-30 20:35:17,105 - DEBUG - Got answer: [{'image': 'localhost:31111/legion_model/test-summation:1.0-180830135752.2.8f237a9', 'model': 'test-summation', 'model_api_info': None, 'model_api_ok': None, 'namespace': 'company-a', 'ready_replicas': 1, 'scale': 1, 'status': 'ok', 'version': '1.0'}] with …
```

[#399] Add detailed legionctl logs

---

legion/legion/edi/server.py
legion/legion/external/edi.py
legion/legion/k8s/enclave.py
tests/robot/4_check_edi.robot

This closes #382: PR adds retries for legionctl -> edi requests and adds analyzing current deployments on scale procedure

[#382] Add retries to legionctl tool

---

examples/Sklearn-Income/Jenkinsfile
examples/Sklearn-Income/tests/test_basic.py
tests/robot/2_check_models.robot

This fixes Jenkins Robot tests because without tests for the Sklearn-income we did not have any metrics in the grafana and test failed.

[#412] Fixes Jenkins Robot tests for the Sklearn-income model

---

tests/robot/5_check_edi_multi_versioned_models.robot

The case was 
'demo-abc-model |nexus-local.cc.epm.kharlamov.biz:443/legion/test-bare-model-api-model-2:0.8.0-20180903130526.23**1.0**29cab7 |1.1     |1     |1     |' 
contains '1.0'
Now we will check with the '|' symbol to be sure.

[#420] Model test expected result fixed

---

legion_test/legion_test/robot/utils.py
tests/robot/resources/keywords.robot

'/securityRealm/commenceLogin' postfix should be used only for the Jenkins component, and be removed from the verification from the other components.
This closes #379

[#379] Fixes incorrect auth urls for components security check

---

tests/robot/4_check_edi.robot
tests/robot/5_check_edi_multi_versioned_models.robot

Increase tests timeout up to 10 minutes in order to get all stderr from legionctl commands.

[#425] Edi test timeouts increased for the debugging in error cases

---

legion/legion/k8s/enclave.py

This closes #408 
This fix adds building of model service object from result of creation function (instead of requesting it)

[#408] Return model service after creation

---

deploy/legionPipeline.groovy
legion_test/legion_test/process_reporter.py

This closes #428.
This adds listener to Robot that will kill all active process and will gather their streams if test fails.

[#428] Add timed out processes log gathering in Robot tests

---

k8s/edge/Dockerfile

Build of Edge docker image failed when we started it without cache, but compelted successfully on current jenkins due to cache. Adding of cffi package fixed the issue.
It's impossible for now to understand what is the reason of this issue, and what package changed.
This PR closes #442

[#441] Added cffi apk package for Edge docker image

---

k8s/jenkins/Dockerfile

This PR closes #455 .
Jenkins has been recently updated (2018-09-12):
https://jenkins.io/changelog-stable/#v2.138.1
And API Token logic has been changed, same as UI:
_Replace single per-user API token with new system of multiple, revocable, unrecoverable API tokens with usage tracking._
Robot tests are not able to get Jenkins API Token due to changed UI.

[#455] Locked Jenkins version to 2.121.3

---

Jenkinsfile
legion/analyze_code.sh
legion/legion/k8s/definitions.py
legion/legion/k8s/services.py
legion/legion/utils.py
legion/tests/test_utils_other.py

[#438] Fix accessing unknown deployments

---

deploy/helms/airflow/templates/worker-rbac.yaml

Added appropriate permissions to Airflow worker so it will be able to create and save ConfigMaps.
This PR closes #443

[#443] Modified Airflow worker permissions to enable ConfigMap creation

---

deploy/helms/airflow/templates/credentials.yaml
deploy/helms/airflow/templates/worker-rbac.yaml
legion_airflow/legion_airflow/hooks/k8s_base_hook.py

[#504] Airflow DAGs unable to read credentials from k8s secret 

---

tests/robot/resources/keywords.robot

This PR fixes temporary #510 . It was agreed to implement smarter solution after Airflow upgrade.

[#510] Disabled test that triggers Airflow tasks

---

tests/robot/resources/keywords.robot

Verify auth page presence only by 'Log in' keyword in the page code.

[#561] Unify the check of security enabled feature for components

---

deploy/ansible/roles/k8s_resources/templates/autoscaler.yaml.j2
deploy/ci-infra.Jenkinsfile
examples/Vertical-Scaling/performance.Jenkinsfile
legion_test/legion_test/robot/k8s.py
legion_test/legion_test/templates/jenkins_performance_job.tmpl
tests/robot/resources/keywords.robot
tests/robot/tests/1_common/1.1_check_clusterwide.robot
tests/robot/tests/2_jenkins_models/2.0_check_jenkins_models.robot

Now we get nodes count before test -> 
request resources for new node creation -> 
check that new node was created -> 
check that new node was scaled down (7 min timeout, every 5 sec check)

[#518] [#511] Scale down node after vertical scaling test

---

deploy/ansible/roles/legion_enclave/templates/legion-values.yaml.j2
deploy/helms/legion/templates/edge/edge-server.yaml
deploy/helms/legion/values.yaml
deploy/profiles/profiles_template.yaml
k8s/edge/nginx.conf.ltmpl
legion/legion/template_plugins/os_environ.py

This PR closes #549 
1. Passed environment variable to Edge pod based on property in profile file
2. Created **os_environ** template plugin
3. Updated nginx.conf template, to read **ENABLE_HOME_PAGE** environment variable
4. Changed Edge liveness probe, because edge home page returns 404 when home page is disabled

[#549] Disable Edge home page in Nginx config based on profile parameter

---

legion_test/legion_test/robot/airflow.py
legion_test/legion_test/robot/jenkins.py

This is needed for the ETL tests on the customer side.
- accessing airflow and jenkins by custom dex auth credentials (not static user)
- working with airflow DAGS (waiting finished and run, get DAG state)  
This will be needed for #322

[#546] Extend airflow and jenkins test classes for airflow tests

---

legion_test/legion_test/robot/flower.py
legion_test/legion_test/robot/k8s.py
tests/robot/resources/keywords.robot
tests/robot/tests/1_common/1.3_check_flower.robot

Closes #602 
Exception raises now if workers/replicas are not ready.
Waiting preconditions for tests added.

[#602] Normalize flower tests methods

---

deploy/ansible/roles/legion_enclave/templates/airflow-values.yaml.j2
deploy/helms/airflow/templates/configuration.yaml
legion_airflow/legion_airflow/hooks/s3_handler.py
legion_airflow/legion_airflow/hooks/s3_hook.py

This PR closes #270 and fixes inaccessible logs in Airflow Web.

[#270] Fixed S3Hook to work without connection_id

---

deploy/ansible/roles/legion_enclave/templates/legion-values.yaml.j2
deploy/helms/legion/templates/metrics/grafana.yaml
deploy/helms/legion/values.yaml
deploy/profiles/legion-ci-app.epm.kharlamov.biz.yml
deploy/profiles/legion-ci-infra.epm.kharlamov.biz.yml
deploy/profiles/legion-ci.epm.kharlamov.biz.yml
deploy/profiles/legion-demo.epm.kharlamov.biz.yml
deploy/profiles/legion-dev.epm.kharlamov.biz.yml
deploy/profiles/legion-test.epm.kharlamov.biz.yml
deploy/profiles/profiles_template.yaml
legion/.pylintrc
legion/analyze_code.sh
legion/legion/k8s/__init__.py
legion/legion/k8s/properties.py
legion/legion/k8s/utils.py
legion_test/legion_test/utils.py
tests/python/test_k8s_introspection.py
tests/python/test_k8s_model_operations.py
tests/python/test_k8s_properties_storages.py
tests/python/test_k8s_watching.py

This closes #479 
This filters k8s events that script gets on start and on watcher restarts

[#479] Remove redundadnt k8s properties changes

---

deploy/ansible/roles/k8s_resources/templates/ingress-aws.yml.j2
legion/legion/serving/config_default.py

#269 
Request size limit was increased to 100MB. According to a bug, there were problem with 20MB request.

[#269] Request size limit in Flask is increased

---

legion/legion/model/client.py
legion/legion/model/types.py
legion/tests/test_deploy.py
legion/tests/test_models/columns_model/run.py

* Added DataFrame column ordering in `build_df` function based on passed `columns_map` order.
* Added test for DataFrame column ordering check
* Fixed docstring for `_prepare_invoke_request`

[#656] Keep DataFrame column order for export_df

---

k8s/edge/Dockerfile

We cannot use the wheel format of python packets in an alpine because
of musl. There are errors with building pandas package from sources.
A root cause does not found.
This closes #685

[#685] Fixed the problem with importing of pandas on edge service

---

k8s/edge/nginx.conf.ltmpl
legion/legion/edi/server.py
legion/legion/external/edi.py
tests/robot/resources/keywords.robot
tests/robot/tests/2_jenkins_models/2.0_check_jenkins_models.robot
tests/robot/tests/3_edi_one_model/3.0_check_edi_one_model.robot

This closes #666.
This renames `version` to `model_version` in EDI `generate_token` endpoint

[#666] Rename version to model_version

---

deploy/helms/legion-core/templates/metrics/grafana.yaml
deploy/helms/legion/templates/metrics/grafana.yaml
legion/legion/edi/server.py
legion/legion/external/grafana.py

By default grafana uses the sqlite database. Many concurrent
connections can be issue. For example, deletion of a dashboard response
404 status code, when the dashboard presents.
PR fixes this comment https://github.com/legion-platform/legion/issues/714#issuecomment-451081771

[#714] decrease number of requests to grafana and increase cpu

---

legion_test/legion_test/robot/grafana.py

[#714] Change to 60min delay in metrics requests

---

legion_test/legion_test/robot/grafana.py

We save start time of test suite in the grafana library to calculate
`from` parameter later.

[714] Fixed hardcoded `from` parameter in the request to graphite

---

k8s/edge/request_id_generator.lua

This closes #762.
Using this patch new data will be added to seed: bytes from `/dev/urandom` which will be different for different time slices.

[#762] Add using of /dev/urandom for EDGE's seed generation
